ALTER TABLE drivers ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS bank_account_iban VARCHAR(50);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS bank_account_name VARCHAR(100);
