// Comprehensive Automotive Parts Taxonomy for QScrap
// Covers ALL automotive categories for Used, Commercial, and Genuine OEM parts
// 2026 Edition - Includes Modern ADAS, EV, Hybrid Systems

export const PART_CATEGORIES = [
    // Powertrain & Performance
    'Engine & Components',
    'Transmission & Drivetrain',
    'Turbo & Supercharger',
    'Fuel System',
    'Exhaust & Emission System',
    'Cooling System',

    // Chassis & Movement
    'Suspension & Steering',
    'Brakes & ABS',
    'Wheels & Tires',
    'Axles & Differential',

    // Body & Structure

    'Body Panels & Bumpers',
    'Doors & Fenders',
    'Glass & Windows',
    'Lights & Lamps',
    'Grilles & Trim',
    'Mirrors & Accessories',

    // Interior
    'Seats & Upholstery',
    'Dashboard & Instruments',
    'Center Console & Storage',
    'Interior Trim & Carpet',
    'Climate Control (HVAC)',

    // Electrical & Electronics
    'Battery & Charging',
    'Alternator & Starter',
    'Wiring & Fuses',
    'Audio & Infotainment',
    'Navigation & Display',
    'Lighting Control',

    // Safety Systems
    'Airbags & SRS',
    'Seatbelts & Restraints',
    'Anti-theft & Security',

    // Modern Tech & ADAS
    'Cameras & Sensors',
    'Radar & Lidar Systems',
    'Parking Assist',
    'Adaptive Cruise Control',
    'Lane Keep Assist',

    // Electric & Hybrid
    'EV Battery Packs',
    'Electric Motors',
    'Inverters & Converters',
    'Charging Components',
    'Hybrid Systems',

    // Accessories & Misc
    'Roof Racks & Carriers',
    'Towing & Hitches',
    'Performance Parts',
    'Off-Road & 4x4',
    'Other Parts',
];

export const PART_SUBCATEGORIES: Record<string, string[]> = {
    // Powertrain & Performance
    'Engine & Components': [
        'Complete Engine Assembly',
        'Cylinder Head',
        'Engine Block (Short/Long)',
        'Crankshaft',
        'Camshaft',
        'Pistons & Rings',
        'Connecting Rods',
        'Timing Chain/Belt',
        'Valve Cover',
        'Oil Pan',
        'Intake Manifold',
        'Exhaust Manifold',
        'Engine Mount',
        'Flywheel',
        'Harmonic Balancer',
        'Oil Pump',
        'Water Pump',
    ],
    'Transmission & Drivetrain': [
        'Automatic Transmission',
        'Manual Transmission',
        'CVT Transmission',
        'Dual-Clutch Transmission (DCT)',
        'Transmission Control Module (TCM)',
        'Torque Converter',
        'Clutch Kit',
        'Pressure Plate',
        'Release Bearing',
        'Driveshaft',
        'CV Axle',
        'Transfer Case',
        'Propeller Shaft',
        'Universal Joint',
        'Shift Cable',
        'Shift Knob',
    ],
    'Turbo & Supercharger': [
        'Turbocharger Assembly',
        'Supercharger',
        'Intercooler',
        'Wastegate',
        'Blow-off Valve',
        'Boost Controller',
        'Turbo Manifold',
        'Downpipe',
    ],
    'Fuel System': [
        'Fuel Pump',
        'Fuel Injector',
        'Fuel Tank',
        'Fuel Rail',
        'Fuel Pressure Regulator',
        'Throttle Body',
        'Fuel Filter',
        'Fuel Cap',
        'Fuel Filler Neck',
        'Fuel Lines',
        'Gas Pedal',
    ],
    'Exhaust & Emission System': [
        'Catalytic Converter',
        'Muffler',
        'Resonator',
        'Exhaust Pipe',
        'Header/Manifold',
        'EGR Valve',
        'DPF (Diesel Particulate Filter)',
        'SCR System (Urea)',
        'Exhaust Flange',
        'Exhaust Hanger',
        'Tail Pipe',
    ],
    'Cooling System': [
        'Radiator',
        'Water Pump',
        'Thermostat',
        'Radiator Fan',
        'Cooling Fan Motor',
        'Radiator Hose',
        'Overflow Tank',
        'Radiator Cap',
        'Temperature Sensor',
    ],

    // Chassis & Movement
    'Suspension & Steering': [
        'Shock Absorber',
        'Strut Assembly',
        'Coil Spring',
        'Leaf Spring',
        'Control Arm (Upper/Lower)',
        'Ball Joint',
        'Tie Rod End',
        'Steering Rack',
        'Power Steering Pump',
        'Steering Column',
        'Steering Wheel',
        'Sway Bar (Anti-roll Bar)',
        'Sway Bar Link',
        'Wheel Hub Assembly',
        'Wheel Bearing',
        'Spindle/Knuckle',
        'Air Suspension Compressor',
        'Steering Coupling',
    ],
    'Brakes & ABS': [
        'ABS Module',
        'ABS Pump',
        'Brake Caliper',
        'Brake Rotor/Disc',
        'Brake Pad',
        'Brake Drum',
        'Brake Shoe',
        'Master Cylinder',
        'Brake Booster',
        'Brake Line',
        'Brake Hose',
        'Parking Brake Cable',
        'Parking Brake Actuator',
        'Brake Proportioning Valve',
        'Wheel Speed Sensor',
    ],
    'Wheels & Tires': [
        'Alloy Wheel',
        'Steel Wheel',
        'Tire (New)',
        'Tire (Used)',
        'Spare Tire',
        'TPMS Sensor',
        'Wheel Center Cap',
        'Lug Nuts',
        'Wheel Lock Set',
        'Run-Flat Tire',
    ],
    'Axles & Differential': [
        'Front Axle Assembly',
        'Rear Axle Assembly',
        'Differential',
        'Limited Slip Differential',
        'Axle Shaft',
        'CV Joint',
        'Axle Bearing',
        'Ring & Pinion Gear',
    ],

    // Body & Structure
    'Body Panels & Bumpers': [
        'Front Bumper Cover',
        'Rear Bumper Cover',
        'Bumper Reinforcement',
        'Bumper Bracket',
        'Side Skirt',
        'Rocker Panel',
        'Mud Flap',
        'Splash Shield',
    ],
    'Doors & Fenders': [
        'Front Door (Left/Right)',
        'Rear Door (Left/Right)',
        'Front Fender',
        'Rear Quarter Panel',
        'Door Shell',
        'Door Handle (Exterior)',
        'Door Handle (Interior)',
        'Door Lock Actuator',
        'Door Latch',
        'Door Hinge',
        'Door Check Strap',
        'Hood',
        'Trunk Lid',
        'Tailgate',
        'Liftgate',
    ],
    'Glass & Windows': [
        'Windshield',
        'Front Door Glass',
        'Rear Door Glass',
        'Quarter Glass',
        'Back Glass/Rear Window',
        'Sunroof Glass',
        'Moonroof Assembly',
        'Window Regulator',
        'Window Motor',
        'Window Switch',
        'Window Track',
        'Windshield Wiper Motor',
        'Wiper Arm',
        'Wiper Blade',
        'Washer Pump',
        'Washer Reservoir',
    ],
    'Lights & Lamps': [
        'Headlight Assembly',
        'LED Headlight',
        'HID Headlight',
        'Halogen Headlight',
        'Taillight Assembly',
        'Fog Light',
        'Turn Signal Light',
        'Side Marker Light',
        'License Plate Light',
        'Dome Light',
        'Map Light',
        'Door Courtesy Light',
        'Trunk Light',
        'Third Brake Light',
        'Daytime Running Light (DRL)',
    ],
    'Grilles & Trim': [
        'Front Grille',
        'Lower Grille',
        'Side Vent',
        'Chrome Trim',
        'Body Molding',
        'Window Molding',
        'Door Molding',
        'Emblem/Badge',
        'Antenna',
    ],
    'Mirrors & Accessories': [
        'Side Mirror Assembly',
        'Mirror Glass',
        'Mirror Motor',
        'Rearview Mirror',
        'Blind Spot Mirror',
        'Mirror Cover/Cap',
        'Tow Mirror',
    ],

    // Interior
    'Seats & Upholstery': [
        'Front Seat (Driver/Passenger)',
        'Rear Seat Bench',
        'Seat Frame',
        'Seat Cushion',
        'Seat Back',
        'Headrest',
        'Seat Belt',
        'Seat Belt Buckle',
        'Seat Cover',
        'Seat Motor',
        'Lumbar Support',
        'Seat Heater',
        'Seat Cooler',
    ],
    'Dashboard & Instruments': [
        'Dashboard Assembly',
        'Instrument Cluster',
        'Speedometer',
        'Tachometer',
        'Gauge Cluster',
        'Head-Up Display (HUD)',
        'Steering Wheel',
        'Steering Column Shroud',
        'Glove Box',
        'Driver Knee Airbag Panel',
    ],
    'Center Console & Storage': [
        'Center Console',
        'Armrest',
        'Cup Holder',
        'Storage Compartment',
        'Gear Shifter',
        'Shift Boot',
        'Parking Brake Handle',
    ],
    'Interior Trim & Carpet': [
        'Door Panel',
        'Door Trim',
        'Pillar Trim (A/B/C/D)',
        'Headliner',
        'Carpet Set',
        'Floor Mat',
        'Trunk Liner',
        'Cargo Cover',
        'Sun Visor',
        'Grab Handle',
        'Coat Hook',
    ],
    'Climate Control (HVAC)': [
        'A/C Compressor',
        'Condenser',
        'Evaporator Core',
        'Heater Core',
        'Blower Motor',
        'HVAC Control Panel',
        'Climate Control Module',
        'A/C Evaporator',
        'Expansion Valve',
        'Receiver Drier',
        'Cabin Air Filter',
    ],

    // Electrical & Electronics
    'Battery & Charging': [
        '12V Battery',
        'Battery Cable',
        'Battery Tray',
        'Battery Terminal',
        'Battery Hold-Down',
    ],
    'Alternator & Starter': [
        'Alternator',
        'Starter Motor',
        'Starter Solenoid',
        'Voltage Regulator',
    ],
    'Wiring & Fuses': [
        'Wiring Harness (Engine)',
        'Wiring Harness (Body)',
        'Fuse Box',
        'Relay',
        'Circuit Breaker',
        'Ground Strap',
        'Connector',
    ],
    'Audio & Infotainment': [
        'Head Unit/Radio',
        'Amplifier',
        'Speaker (Front/Rear)',
        'Subwoofer',
        'Antenna Module',
        'CD/DVD Player',
        'Touch Screen Display',
    ],
    'Navigation & Display': [
        'GPS Navigation Module',
        'Navigation Display',
        'Infotainment Screen',
        'Rear Seat Entertainment',
    ],
    'Lighting Control': [
        'Headlight Switch',
        'Turn Signal Switch',
        'Dimmer Switch',
        'Hazard Switch',
        'Lighting Control Module',
    ],

    // Safety Systems
    'Airbags & SRS': [
        'Driver Airbag',
        'Passenger Airbag',
        'Side Airbag',
        'Curtain Airbag',
        'Knee Airbag',
        'SRS Control Module',
        'Airbag Clockspring',
        'Airbag Sensor',
    ],
    'Seatbelts & Restraints': [
        'Seat Belt Retractor',
        'Seat Belt Buckle',
        'Seat Belt Pretensioner',
        'Child Seat Anchor',
    ],
    'Anti-theft & Security': [
        'Immobilizer',
        'Alarm Module',
        'Door Lock Cylinder',
        'Trunk Lock',
        'Ignition Lock Cylinder',
        'Key Fob',
        'Transponder Key',
    ],

    // Modern Tech & ADAS
    'Cameras & Sensors': [
        'Backup Camera',
        'Front Camera',
        'Side Camera',
        '360° Camera System',
        'Parking Sensor',
        'Ultrasonic Sensor',
        'Rain Sensor',
        'Light Sensor',
    ],
    'Radar & Lidar Systems': [
        'Front Radar',
        'Rear Radar',
        'Corner Radar',
        'Lidar Unit',
        'Radar Control Module',
    ],
    'Parking Assist': [
        'Park Assist Module',
        'Parking Sensor',
        'Park Assist Camera',
        'Self-Parking System',
    ],
    'Adaptive Cruise Control': [
        'ACC Module',
        'ACC Radar',
        'Cruise Control Switch',
        'Distance Sensor',
    ],
    'Lane Keep Assist': [
        'Lane Departure Module',
        'Lane Camera',
        'Steering Assist Motor',
        'Lane Sensor',
    ],

    // Electric & Hybrid
    'EV Battery Packs': [
        'High Voltage Battery',
        'Battery Cell Module',
        'Battery Management System (BMS)',
        'Battery Coolant Pump',
        'Battery Heater',
    ],
    'Electric Motors': [
        'Traction Motor',
        'Drive Motor',
        'Generator Motor',
        'Motor Controller',
    ],
    'Inverters & Converters': [
        'DC-DC Converter',
        'Inverter Assembly',
        'On-Board Charger',
        'Power Control Unit',
    ],
    'Charging Components': [
        'Charge Port',
        'Charge Cable',
        'Charging Inlet',
        'Charge Controller',
    ],
    'Hybrid Systems': [
        'Hybrid Battery Pack',
        'Hybrid Control Module',
        'Electric Water Pump',
        'Hybrid Transmission',
    ],

    // Accessories & Misc
    'Roof Racks & Carriers': [
        'Roof Rack',
        'Cross Bar',
        'Cargo Box',
        'Ski Rack',
        'Bike Rack',
    ],
    'Towing & Hitches': [
        'Trailer Hitch',
        'Tow Hook',
        'Towing Wiring',
        'Ball Mount',
    ],
    'Performance Parts': [
        'Cold Air Intake',
        'Performance Exhaust',
        'Sway Bar Upgrade',
        'Coilover Kit',
        'Short Shifter',
    ],
    'Off-Road & 4x4': [
        'Skid Plate',
        'Rock Slider',
        'Winch',
        '4x4 Transfer Case',
        'Lift Kit',
        'Off-Road Bumper',
    ],
    'Other Parts': [
        'Gas Cap',
        'Jack',
        'Spare Tire Tools',
        'Floor Jack',
        'Miscellaneous',
    ],
};

// Helper functions
export const getAllCategories = (): string[] => {
    return PART_CATEGORIES;
};

export const getSubcategoriesForCategory = (category: string): string[] => {
    return PART_SUBCATEGORIES[category] || [];
};
